apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: gabrielrojas/jenkinssummit
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 31000
          volumeMounts:
            - name: jenkins-persistent-storge
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-persistent-storge
          emptyDir: {}