apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      name: http-port
    - port: 31000
      targetPort: 31000
      nodePort: 31000
      name: jnlp-port
  selector:
    app: jenkins