node ('Windows2016') {
    stage ('Test Pass') {
        powershell 'Invoke-OperationValidation'
    }
        
    stage ('Test fails'){
        powershell 'invoke-pester c:\test_gabe.Tests.ps1 -OutputFormat NunitXML -OutputFile report.xml -EnableExit'
    }
    
}